[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]] # カラーテーマ
repo = 'jacoborus/tender.vim'
hook_add = '''
colorscheme tender
'''

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# ブランチ名をlightlineに表示する
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ripgrepコマンド
[[plugins]]
repo = 'kyoh86/vim-ripgrep'

# C-j, C-kで高速縦移動
[[plugins]]
repo = 'haya14busa/vim-edgemotion'
hook_add = '''
nmap <C-j> <Plug>(edgemotion-j)
nmap <C-k> <Plug>(edgemotion-k)
'''

# 検索結果件数をバーチャル表示
[[plugins]]
repo = 'kevinhwang91/nvim-hlslens'
hook_add = '''
lua << EOF
  local kopts = {noremap = true, silent = true}

  vim.api.nvim_set_keymap('n', 'n',
    [[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
  vim.api.nvim_set_keymap('n', 'N',
    [[<Cmd>execute('normal! ' . v:count1 . 'N')<CR><Cmd>lua require('hlslens').start()<CR>]],
    kopts)
  vim.api.nvim_set_keymap('n', '*', [[*<Cmd>lua require('hlslens').start()<CR>]], kopts)
  vim.api.nvim_set_keymap('n', '#', [[#<Cmd>lua require('hlslens').start()<CR>]], kopts)
  vim.api.nvim_set_keymap('n', 'g*', [[g*<Cmd>lua require('hlslens').start()<CR>]], kopts)
  vim.api.nvim_set_keymap('n', 'g#', [[g#<Cmd>lua require('hlslens').start()<CR>]], kopts)

  vim.api.nvim_set_keymap('n', '<Leader>l', ':noh<CR>', kopts)
EOF
'''

# スクロールバーを追加
[[plugins]]
repo = 'petertriho/nvim-scrollbar'
hook_add = '''
lua << EOF
  require("scrollbar").setup()
  require("scrollbar.handlers.search").setup()
EOF
'''

# fコマンドでのjumpをわかりやすく
[[plugins]]
repo = 'unblevable/quick-scope'
hook_add = '''
let g:qs_highlight_on_keys = ['f', 'F', 't', 'T']
'''

