[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]] # 非同期処理
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]] # カラーテーマ
repo = 'jacoborus/tender.vim'
hook_add = '''
  colorscheme tender
'''

# statusline
[[plugins]]
repo = 'itchyny/lightline.vim'

# ブランチ名をlightlineに表示する
[[plugins]]
repo = 'itchyny/vim-gitbranch'

# インデントを可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# 無駄な空白をハイライト
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

# ripgrepコマンド
[[plugins]]
repo = 'kyoh86/vim-ripgrep'

