[[plugins]] # ローカル変数ハイライト
repo = 'todesking/ruby_hl_lvar.vim'

[[plugins]]
repo = 'elixir-lang/vim-elixir'
on_ft = 'elixir'

[[plugins]]
repo = 'thinca/vim-ref'
on_ft = 'elixir'

[[plugins]]
repo = 'awetzel/elixir.nvim'
build = './install.sh'
on_ft = 'elixir'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
